# Generated by Django 2.1.7 on 2019-04-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_cv', '0006_hobbie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=80)),
                ('message', models.TextField(null=True)),
                ('forward', models.BooleanField()),
            ],
            options={
                'db_table': 'email',
            },
        ),
    ]
